# Generated by Django 4.0.2 on 2022-02-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
    ]
